# generated by datamodel-codegen:
#   filename:  open-ai.yaml
#   timestamp: 2024-01-16T12:17:19+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class GetEventResponse(BaseModel):
    events: Optional[List[str]] = Field(None, description='The list of events')
